<a href="https://colab.research.google.com/github/davidriveraarbelaez/BDIIUCP/blob/main/Limpieza_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hola mundo

In [ ]:
print("Hola mundo")

URL dataset: https://www.kaggle.com/datasets/carolzhangdc/imdb-5000-movie-dataset

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("carolzhangdc/imdb-5000-movie-dataset")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.12), please consider upgrading to the latest version (0.3.13).
Downloading from https://www.kaggle.com/api/v1/datasets/download/martj42/international-football-results-from-1872-to-2017?dataset_version_number=97...

100%|██████████| 1.15M/1.15M [00:00<00:00, 83.3MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/martj42/international-football-results-from-1872-to-2017/versions/97

In [ ]:
path

'/root/.cache/kagglehub/datasets/martj42/international-football-results-from-1872-to-2017/versions/97'

In [2]:
import pandas as pd
df = pd.read_csv('/content/movie_metadata.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5029 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [ ]:
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0$,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0$,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0$,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0$,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,0.0$,NaN,12.0,7.1,NaN,0

In [ ]:
df['budget'].head()

In [ ]:
print(df.columns)

In [ ]:
df.isnull().sum()

In [4]:
registros_duplicados = df[df.duplicated()]
print(registros_duplicados)

                 color         director_name  num_critic_for_reviews  \
137              Color           David Yates                   248.0
187              Color           Bill Condon                   322.0
204              Color          Hideaki Anno                     1.0
303              Color            Joe Wright                   256.0
389              Color            Josh Trank                   369.0
395              Color             Rob Cohen                   187.0
590              Color          Brett Ratner                   245.0
656              Color        Paul Verhoeven                   196.0
794              Color           Joss Whedon                   703.0
1220             Color   Angelina Jolie Pitt                   322.0
1305             Color         Paul McGuigan                   159.0
1449             Color         Albert Hughes                   208.0
2169             Color         Paul McGuigan                    98.0
2292             Color              Frank Oz                   168.0
2472             Color            Jon Cassar                    45.0
2493   Black and White           Yimou Zhang                   283.0
2533             Color           Neil Burger                   236.0
2562             Color             Jon Lucas                    81.0
2568             Color         Vic Armstrong                   169.0
2619             Color        John Carpenter                   318.0
2771             Color          Ole Bornedal                   264.0
2777             Color        Stephen Frears                    51.0
2798             Color            Shawn Levy                    69.0
2971             Color      John Lee Hancock                   106.0
3117             Color           Guy Ritchie                   151.0
3345             Color          Herbert Ross                    60.0
3452             Color           Paul Haggis                   287.0
3480             Color  Michael Winterbottom                    71.0
3729             Color      Tim Blake Nelson                    92.0
3900             Color                   NaN                     9.0
3915             Color            Wes Craven                   160.0
4182             Color            Rob Zombie                   220.0
4226             Color      William Friedkin                   138.0
4282             Color       Kenneth Branagh                    85.0
4313             Color       Bruce McCulloch                    52.0
4408             Color           Yimou Zhang                   101.0
4565             Color        Peter Cattaneo                   122.0
4573             Color            Mel Brooks                    48.0
4631             Color           Danny Boyle                   393.0
4769             Color           Tamra Davis                   111.0
4882             Color            Dan Curtis                     NaN
4927             Color           Jason Stone                    48.0
4942             Color         Paul Schrader                   130.0
4950             Color         David Hewlett                     8.0
4951   Black and White      George A. Romero                   284.0

      duration  director_facebook_likes  actor_3_facebook_likes  \
137      110.0                    282.0                   103.0
187      115.0                    386.0                 12000.0
204      120.0                     28.0                    12.0
303      111.0                    456.0                   394.0
389      100.0                    128.0                    78.0
395      106.0                    357.0                  4000.0
590      101.0                    420.0                   467.0
656      113.0                    719.0                   217.0
794      173.0                      0.0                 19000.0
1220     137.0                  11000.0                   465.0
1305     110.0                    118.0                   287.0
1449     122.0                    117.0                   140.0
2169     114.0                    118.0                    40.0
2292      87.0                      0.0                   548.0
2472      90.0                     78.0                   720.0
2493      80.0                    611.0                   576.0
2533     110.0                    168.0                    96.0
2562     100.0                     24.0                   851.0
2568     110.0                    179.0                   734.0
2619     101.0                      0.0                   598.0
2771      92.0                     30.0                   309.0
2777     119.0                    350.0                   418.0
2798      88.0                    189.0                   799.0
2971     137.0                    102.0                   877.0
3117     104.0                      0.0                  1000.0
3345     107.0                     71.0                   304.0
3452     115.0                    549.0                   911.0
3480     115.0                    187.0                   887.0
3729      95.0                    596.0                   697.0
3900      60.0                      NaN                   904.0
3915     107.0                      0.0                   255.0
4182     119.0                      0.0                   593.0
4226     104.0                    607.0                   109.0
4282     150.0                      0.0                   401.0
4313      85.0                     54.0                   455.0
4408      95.0                    611.0                     3.0
4565      91.0                     11.0                   121.0
4573      92.0                      0.0                   842.0
4631     101.0                      0.0                   888.0
4769      93.0                     33.0                   135.0
4882      99.0                     45.0                   224.0
4927     108.0                     14.0                   826.0
4942      93.0                    261.0                   697.0
4950      88.0                    686.0                   405.0
4951      96.0                      0.0                    56.0

             actor_2_name  actor_1_facebook_likes        gross  \
137   Alexander Skarsgård                 11000.0  124051759.0
187       Kristen Stewart                 21000.0  292298923.0
204     Shin'ya Tsukamoto                   544.0          NaN
303       Cara Delevingne                 20000.0   34964818.0
389         Reg E. Cathey                   596.0   56114221.0
395            Vin Diesel                 23000.0  144512310.0
590          Rufus Sewell                 12000.0   72660029.0
656        Rachel Ticotin                   605.0  119412921.0
794     Robert Downey Jr.                 26000.0  623279547.0
1220       Jack O'Connell                   769.0  115603980.0
1305      Spencer Wilding                 11000.0    5773519.0
1449        Jason Flemyng                 40000.0   31598308.0
2169  Christopher Cousins                   489.0   12831121.0
2292         Ewen Bremner                 22000.0    8579684.0
2472      Landon Liboiron                  2000.0          NaN
2493  Tony Chiu Wai Leung                  5000.0      84961.0
2533         Eddie Marsan                  3000.0   39825798.0
2562        Jay Hernandez                 15000.0   55461307.0
2568         Lea Thompson                 12000.0   13998282.0
2619     Donald Pleasence                  2000.0   47000000.0
2771    Madison Davenport                   941.0   49122319.0
2777        Peter Capaldi                 18000.0   34700000.0
2798        Donald Faison                   934.0   47811275.0
2971          Marc Blucas                  2000.0   22406362.0
3117            Brad Pitt                 26000.0   30093107.0
3345           Chris Penn                   967.0   80000000.0
3452       Loretta Devine                  3000.0   54557348.0
3480         Sarah Polley                 14000.0     403932.0
3729        Andrew Keegan                  1000.0   16017403.0
3900       Dylan Minnette                  1000.0          NaN
3915          Emily Meade                   798.0   14637490.0
4182           Tyler Mane                   908.0   33386128.0
4226         Fernando Rey                   813.0          NaN
4282        Brian Blessed                   597.0    4414535.0
4313       Megan Mullally                   985.0   13973532.0
4408               Ni Yan                     9.0     190666.0
4565            Mark Addy                  1000.0   45857453.0
4573           Sid Caesar                  1000.0          NaN
4631      Spencer Wilding                  3000.0    2319187.0
4769    Katherine Boecher                  1000.0   37188667.0
4882       Campbell Scott                  1000.0          NaN
4927        Ellen Burstyn                  2000.0          NaN
4942             Ruby Dee                   783.0          NaN
4950        David Hewlett                   847.0          NaN
4951          Duane Jones                   125.0          NaN

                                     genres  ... num_user_for_reviews  \
137          Action|Adventure|Drama|Romance  ...                239.0
187         Adventure|Drama|Fantasy|Romance  ...                329.0
204    Action|Adventure|Drama|Horror|Sci-Fi  ...                 13.0
303                Adventure|Family|Fantasy  ...                186.0
389                 Action|Adventure|Sci-Fi  ...                695.0
395                   Action|Crime|Thriller  ...                988.0
590                        Action|Adventure  ...                269.0
656                           Action|Sci-Fi  ...                391.0
794                 Action|Adventure|Sci-Fi  ...               1722.0
1220              Biography|Drama|Sport|War  ...                351.0
1305           Drama|Horror|Sci-Fi|Thriller  ...                 91.0
1449                Horror|Mystery|Thriller  ...                541.0
2169         Drama|Mystery|Romance|Thriller  ...                298.0
2292                                 Comedy  ...                199.0
2472                          Drama|Western  ...                 49.0
2493               Action|Adventure|History  ...                841.0
2533         Drama|Mystery|Romance|Thriller  ...                645.0
2562                                 Comedy  ...                 46.0
2568  Action|Drama|Fantasy|Mystery|Thriller  ...                374.0
2619                        Horror|Thriller  ...               1191.0
2771                        Horror|Thriller  ...                162.0
2777                          Drama|Romance  ...                143.0
2798                Adventure|Comedy|Family  ...                 99.0
2971              Drama|History|War|Western  ...                267.0
3117                           Comedy|Crime  ...                726.0
3345                    Drama|Music|Romance  ...                113.0
3452                   Crime|Drama|Thriller  ...               1624.0
3480                  Drama|Romance|Western  ...                 92.0
3729                 Drama|Romance|Thriller  ...                153.0
3900                          Drama|Fantasy  ...                 47.0
3915                Horror|Mystery|Thriller  ...                136.0
4182                                 Horror  ...                491.0
4226            Action|Crime|Drama|Thriller  ...                280.0
4282                                  Drama  ...                224.0
4313                           Comedy|Crime  ...                 92.0
4408                           Comedy|Drama  ...                 20.0
4565                     Comedy|Drama|Music  ...                174.0
4573                                 Comedy  ...                131.0
4631           Crime|Drama|Mystery|Thriller  ...                212.0
4769                           Comedy|Drama  ...                578.0
4882                        Fantasy|Romance  ...                 56.0
4927                               Thriller  ...                 28.0
4942                Fantasy|Horror|Thriller  ...                106.0
4950                                 Comedy  ...                 46.0
4951                   Drama|Horror|Mystery  ...                580.0

      language  country  content_rating       budget  title_year  \
137    English      USA           PG-13  180000000.0      2016.0
187    English      USA           PG-13  120000000.0      2012.0
204   Japanese    Japan             NaN          NaN      2016.0
303    English      USA              PG  150000000.0      2015.0
389    English      USA           PG-13  120000000.0      2015.0
395    English      USA           PG-13   38000000.0      2001.0
590    English      USA           PG-13  100000000.0      2014.0
656    English      USA               R   65000000.0      1990.0
794    English      USA           PG-13  220000000.0      2012.0
1220   English      USA           PG-13   65000000.0      2014.0
1305   English      USA           PG-13   40000000.0      2015.0
1449   English      USA               R   35000000.0      2001.0
2169   English      USA           PG-13   30000000.0      2004.0
2292   English      USA               R    9000000.0      2007.0
2472   English   Canada               R   11000000.0      2015.0
2493  Mandarin    China           PG-13   31000000.0      2002.0
2533   English      USA           PG-13   16000000.0      2006.0
2562   English      USA               R   20000000.0      2016.0
2568   English      USA           PG-13   16000000.0      2014.0
2619   English      USA               R     300000.0      1978.0
2771   English      USA           PG-13   14000000.0      2012.0
2777   English      USA               R   14000000.0      1988.0
2798   English      USA              PG   15000000.0      2002.0
2971   English      USA           PG-13  107000000.0      2004.0
3117   English       UK               R    6000000.0      2000.0
3345   English      USA              PG    8200000.0      1984.0
3452   English  Germany               R    6500000.0      2004.0
3480   English       UK               R   20000000.0      2000.0
3729   English      USA               R    5000000.0      2001.0
3900   English      USA           TV-MA          NaN         NaN
3915   English      USA               R   25000000.0      2010.0
4182   English      USA               R   15000000.0      2009.0
4226   English      USA               R    1800000.0      1971.0
4282   English       UK           PG-13   18000000.0      1996.0
4313   English      USA           PG-13   25000000.0      2002.0
4408  Mandarin    China               R          NaN      2009.0
4565   English       UK               R    3500000.0      1997.0
4573   English      USA               R   11000000.0      1981.0
4631   English       UK               R   20000000.0      2013.0
4769   English      USA           PG-13   12000000.0      2002.0
4882   English      USA         Unrated          NaN      1998.0
4927   English      USA               R          NaN      2014.0
4942   English      USA               R   18000000.0      1982.0
4950   English   Canada             NaN     120000.0      2007.0
4951   English      USA         Unrated     114000.0      1968.0

     actor_2_facebook_likes imdb_score  aspect_ratio movie_facebook_likes
137                 10000.0        6.6          2.35                29000
187                 17000.0        5.5          2.35                65000
204                   106.0        8.2          2.35                    0
303                   548.0        5.8          2.35                24000
389                   360.0        4.3          2.35                41000
395                 14000.0        6.7          2.35                14000
590                  3000.0        6.0          2.35                21000
656                   308.0        7.5          1.85                    0
794                 21000.0        8.1          1.85               123000
1220                  698.0        7.2          2.35                35000
1305                 1000.0        6.0          2.35                11000
1449                 1000.0        6.8          2.35                    0
2169                   93.0        7.0          2.35                    0
2292                  557.0        7.4          1.85                    0
2472                 1000.0        6.3          2.35                    0
2493                  643.0        7.9          2.35                    0
2533                  979.0        7.6          1.85                15000
2562                 1000.0        6.7           NaN                18000
2568                 1000.0        3.1          2.35                31000
2619                  742.0        7.9          2.35                12000
2771                  459.0        5.9          2.35                17000
2777                17000.0        7.7          1.85                    0
2798                  927.0        5.4          1.85                  896
2971                  973.0        6.0          2.35                  701
3117                11000.0        8.3          1.85                27000
3345                  455.0        6.5          1.85                    0
3452                  912.0        7.9          2.35                18000
3480                  900.0        6.5          2.35                  141
3729                  835.0        6.2          1.85                    0
3900                 1000.0        7.5          1.78                  634
3915                  374.0        4.8          2.35                    0
4182                  764.0        4.9          1.85                 3000
4226                  165.0        7.8          1.85                    0
4282                  591.0        7.8          2.20                    0
4313                  637.0        5.1          1.85                  215
4408                    4.0        5.7          2.35                  784
4565                  891.0        7.2          1.85                    0
4573                  898.0        6.9          2.35                    0
4631                 1000.0        7.0          2.35                23000
4769                  188.0        3.3          1.85                    0
4882                  393.0        7.4          1.33                  515
4927                 1000.0        5.8           NaN                    0
4942                  782.0        6.1          1.85                    0
4950                  686.0        7.0          1.78                  377
4951                  108.0        8.0          1.85                    0

[45 rows x 28 columns]

In [ ]:
duplicados = df.duplicated().sum()
print(duplicados)

45

In [8]:
eliminar_duplicados = df.drop_duplicates()

In [9]:
eliminar_duplicados.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4998 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      4979 non-null   object
 1   director_name              4895 non-null   object
 2   num_critic_for_reviews     4949 non-null   float64
 3   duration                   4983 non-null   float64
 4   director_facebook_likes    4895 non-null   float64
 5   actor_3_facebook_likes     4975 non-null   float64
 6   actor_2_name               4985 non-null   object
 7   actor_1_facebook_likes     4991 non-null   float64
 8   gross                      4124 non-null   float64
 9   genres                     4998 non-null   object
 10  actor_1_name               4991 non-null   object
 11  movie_title                4998 non-null   object
 12  num_voted_users            4998 non-null   int64
 13  cast_total_facebook_likes  4998 non-null   int64
 14  actor_3_name               4975 non-null   object
 15  facenumber_in_poster       4985 non-null   float64
 16  plot_keywords              4846 non-null   object
 17  movie_imdb_link            4998 non-null   object
 18  num_user_for_reviews       4977 non-null   float64
 19  language                   4984 non-null   object
 20  country                    4993 non-null   object
 21  content_rating             4697 non-null   object
 22  budget                     4511 non-null   float64
 23  title_year                 4891 non-null   float64
 24  actor_2_facebook_likes     4985 non-null   float64
 25  imdb_score                 4998 non-null   float64
 26  aspect_ratio               4671 non-null   float64
 27  movie_facebook_likes       4998 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [ ]:
duplicados_despues_drop = eliminar_duplicados.duplicated().sum()
print(f"Duplicados antes: {duplicados}, Duplicados después: {duplicados_despues_drop} ")

Duplicados antes: 45, Duplicados después: 0

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
num_critic_for_reviews,4993.0,1.401943e+02,1.216017e+02,1.00,50.00,110.00,195.00,813.0
duration,5028.0,1.072011e+02,2.519744e+01,7.00,93.00,103.00,118.00,511.0
director_facebook_likes,4939.0,6.865092e+02,2.813329e+03,0.00,7.00,49.00,194.50,23000.0
actor_3_facebook_likes,5020.0,6.450098e+02,1.665042e+03,0.00,133.00,371.50,636.00,23000.0
actor_1_facebook_likes,5036.0,6.560047e+03,1.502076e+04,0.00,614.00,988.00,11000.00,640000.0
gross,4159.0,4.846841e+07,6.845299e+07,162.00,5340987.50,25517500.00,62309437.50,760505847.0
num_voted_users,5043.0,8.366816e+04,1.384853e+05,5.00,8593.50,34359.00,96309.00,1689764.0
cast_total_facebook_likes,5043.0,9.699064e+03,1.816380e+04,0.00,1411.00,3090.00,13756.50,656730.0
facenumber_in_poster,5030.0,1.371173e+00,2.013576e+00,0.00,0.00,1.00,2.00,43.0
num_user_for_reviews,5022.0,2.727708e+02,3.779829e+02,1.00,65.00,156.00,326.00,5060.0
title_year,4935.0,2.002471e+03,1.247460e+01,1916.00,1999.00,2005.00,2011.00,2016.0
actor_2_facebook_likes,5030.0,1.651754e+03,4.042439e+03,0.00,281.00,595.00,918.00,137000.0
imdb_score,5043.0,6.442138e+00,1.125116e+00,1.60,5.80,6.60,7.20,9.5
aspect_ratio,4714.0,2.220403e+00,1.385113e+00,1.18,1.85,2.35,2.35,16.0
movie_facebook_likes,5043.0,7.525965e+03,1.932045e+04,0.00,0.00,166.00,3000.00,349000.0

In [ ]:
mediana_antes = # Validar el impacto de los valores duplicados

In [10]:
mediana = duplicados_despues_drop['duration'].median()
print(mediana)

NameError: name 'duplicados_despues_drop' is not defined

In [ ]:
promedio = variable[''].mean()
print(promedio)

In [11]:
eliminar_duplicados.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4998 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      4979 non-null   object
 1   director_name              4895 non-null   object
 2   num_critic_for_reviews     4949 non-null   float64
 3   duration                   4983 non-null   float64
 4   director_facebook_likes    4895 non-null   float64
 5   actor_3_facebook_likes     4975 non-null   float64
 6   actor_2_name               4985 non-null   object
 7   actor_1_facebook_likes     4991 non-null   float64
 8   gross                      4124 non-null   float64
 9   genres                     4998 non-null   object
 10  actor_1_name               4991 non-null   object
 11  movie_title                4998 non-null   object
 12  num_voted_users            4998 non-null   int64
 13  cast_total_facebook_likes  4998 non-null   int64
 14  actor_3_name               4975 non-null   object
 15  facenumber_in_poster       4985 non-null   float64
 16  plot_keywords              4846 non-null   object
 17  movie_imdb_link            4998 non-null   object
 18  num_user_for_reviews       4977 non-null   float64
 19  language                   4984 non-null   object
 20  country                    4993 non-null   object
 21  content_rating             4697 non-null   object
 22  budget                     4511 non-null   float64
 23  title_year                 4891 non-null   float64
 24  actor_2_facebook_likes     4985 non-null   float64
 25  imdb_score                 4998 non-null   float64
 26  aspect_ratio               4671 non-null   float64
 27  movie_facebook_likes       4998 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [13]:
# Crear un nuevo dataset sin los datos duplicados
df_sin_duplicados = eliminar_duplicados.drop_duplicates()

In [14]:
# Crear un csv nuevo sin los datos duplicados
df_sin_duplicados.to_csv('df_sin_duplicados.csv', index=False)