<a href="https://colab.research.google.com/github/davidriveraarbelaez/BDIIUCP/blob/main/Limpieza_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hola mundo

In [ ]:
print("Hola mundo")

URL dataset: https://www.kaggle.com/datasets/carolzhangdc/imdb-5000-movie-dataset

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("carolzhangdc/imdb-5000-movie-dataset")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.12), please consider upgrading to the latest version (0.3.13).
Downloading from https://www.kaggle.com/api/v1/datasets/download/martj42/international-football-results-from-1872-to-2017?dataset_version_number=97...

100%|██████████| 1.15M/1.15M [00:00<00:00, 83.3MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/martj42/international-football-results-from-1872-to-2017/versions/97

In [2]:
path

'/root/.cache/kagglehub/datasets/martj42/international-football-results-from-1872-to-2017/versions/97'

In [6]:
import pandas as pd
df = pd.read_csv('/content/movie_metadata.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5029 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     5043 non-null   object
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(12), int64(3), object(13)
memory usage: 1.1+ MB

In [7]:
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0$,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0$,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0$,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0$,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,0.0$,NaN,12.0,7.1,NaN,0

In [ ]:
df['budget'].head()

In [ ]:
print(df.columns)

In [ ]:
df.isnull().sum()

In [15]:
duplicados = df.duplicated().sum()
print(duplicados)

45

In [16]:
eliminar_duplicados = df.drop_duplicates()

In [21]:
eliminar_duplicados.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4998 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      4979 non-null   object
 1   director_name              4895 non-null   object
 2   num_critic_for_reviews     4949 non-null   float64
 3   duration                   4983 non-null   float64
 4   director_facebook_likes    4895 non-null   float64
 5   actor_3_facebook_likes     4975 non-null   float64
 6   actor_2_name               4985 non-null   object
 7   actor_1_facebook_likes     4991 non-null   float64
 8   gross                      4124 non-null   float64
 9   genres                     4998 non-null   object
 10  actor_1_name               4991 non-null   object
 11  movie_title                4998 non-null   object
 12  num_voted_users            4998 non-null   int64
 13  cast_total_facebook_likes  4998 non-null   int64
 14  actor_3_name               4975 non-null   object
 15  facenumber_in_poster       4985 non-null   float64
 16  plot_keywords              4846 non-null   object
 17  movie_imdb_link            4998 non-null   object
 18  num_user_for_reviews       4977 non-null   float64
 19  language                   4984 non-null   object
 20  country                    4993 non-null   object
 21  content_rating             4697 non-null   object
 22  budget                     4998 non-null   object
 23  title_year                 4891 non-null   float64
 24  actor_2_facebook_likes     4985 non-null   float64
 25  imdb_score                 4998 non-null   float64
 26  aspect_ratio               4671 non-null   float64
 27  movie_facebook_likes       4998 non-null   int64
dtypes: float64(12), int64(3), object(13)
memory usage: 1.1+ MB

In [19]:
duplicados_despues_drop = eliminar_duplicados.duplicated().sum()
print(f"Duplicados antes: {duplicados}, Duplicados después: {duplicados_despues_drop} ")

Duplicados antes: 45, Duplicados después: 0

In [23]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
num_critic_for_reviews,4993.0,1.401943e+02,1.216017e+02,1.00,50.00,110.00,195.00,813.0
duration,5028.0,1.072011e+02,2.519744e+01,7.00,93.00,103.00,118.00,511.0
director_facebook_likes,4939.0,6.865092e+02,2.813329e+03,0.00,7.00,49.00,194.50,23000.0
actor_3_facebook_likes,5020.0,6.450098e+02,1.665042e+03,0.00,133.00,371.50,636.00,23000.0
actor_1_facebook_likes,5036.0,6.560047e+03,1.502076e+04,0.00,614.00,988.00,11000.00,640000.0
gross,4159.0,4.846841e+07,6.845299e+07,162.00,5340987.50,25517500.00,62309437.50,760505847.0
num_voted_users,5043.0,8.366816e+04,1.384853e+05,5.00,8593.50,34359.00,96309.00,1689764.0
cast_total_facebook_likes,5043.0,9.699064e+03,1.816380e+04,0.00,1411.00,3090.00,13756.50,656730.0
facenumber_in_poster,5030.0,1.371173e+00,2.013576e+00,0.00,0.00,1.00,2.00,43.0
num_user_for_reviews,5022.0,2.727708e+02,3.779829e+02,1.00,65.00,156.00,326.00,5060.0
title_year,4935.0,2.002471e+03,1.247460e+01,1916.00,1999.00,2005.00,2011.00,2016.0
actor_2_facebook_likes,5030.0,1.651754e+03,4.042439e+03,0.00,281.00,595.00,918.00,137000.0
imdb_score,5043.0,6.442138e+00,1.125116e+00,1.60,5.80,6.60,7.20,9.5
aspect_ratio,4714.0,2.220403e+00,1.385113e+00,1.18,1.85,2.35,2.35,16.0
movie_facebook_likes,5043.0,7.525965e+03,1.932045e+04,0.00,0.00,166.00,3000.00,349000.0